import json

# Extract from VJ_Policy_Table_Chatbot.xlsx

faq_data = [
    {"category": "Hành lý", "situation": "Hành lý xách tay (cabin)", "promo_eco_basic": "7kg · 1 kiện 56x36x23cm", "eco_standard": "7kg · 1 kiện 56x36x23cm", "deluxe": "7kg · 1 kiện 56x36x23cm", "skyboss": "10kg · 1 kiện 56x36x23cm", "important_notes": "Thêm 1 phụ kiện nhỏ (túi xách, balo nhỏ) được mang kèm", "risk": 1, "short_answer": "\"Xách tay VJ được 7kg (SkyBoss 10kg), kích thước tối đa 56x36x23cm bạn nhé.\"", "escalate_when": "—"},
    {"category": "Hành lý", "situation": "Hành lý ký gửi (miễn phí)", "promo_eco_basic": "Không có", "eco_standard": "Không có", "deluxe": "Có (theo gói mua)", "skyboss": "30kg", "important_notes": "Promo & Eco cần mua thêm nếu có nhu cầu ký gửi", "risk": 1, "short_answer": "\"Eco Basic/Promo không có hành lý ký gửi miễn phí bạn nhé, cần mua thêm.\"", "escalate_when": "—"},
    {"category": "Hành lý", "situation": "Mua thêm ký gửi — giá", "promo_eco_basic": "Tùy tuyến tùy thời điểm", "eco_standard": "Tùy tuyến tùy thời điểm", "deluxe": "Tùy tuyến tùy thời điểm", "skyboss": "N/A (đã có 30kg)", "important_notes": "Mua lúc đặt vé thường rẻ hơn tại sân bay", "risk": 2, "short_answer": "\"Giá hành lý thêm tùy tuyến, mua lúc đặt vé rẻ hơn ra sân bay bạn nhé.\"", "escalate_when": "Hỏi giá cụ thể theo tuyến → cần API real-time"},
    {"category": "Hành lý", "situation": "Laptop + balo tính mấy kiện?", "promo_eco_basic": "1 kiện nếu gộp vừa 7kg & kích thước", "eco_standard": "1 kiện nếu gộp vừa 7kg & kích thước", "deluxe": "1 kiện nếu gộp vừa 7kg & kích thước", "skyboss": "1 kiện nếu gộp vừa 10kg & kích thước", "important_notes": "Tính tổng cộng không vượt quy định", "risk": 1, "short_answer": "\"Balo và laptop tính chung 1 kiện nếu tổng không quá 7kg và đúng kích thước bạn nhé.\"", "escalate_when": "—"},
    {"category": "Hành lý", "situation": "Pin dự phòng", "promo_eco_basic": "≤20.000mAh · max 2 cái · chỉ xách tay", "eco_standard": "≤20.000mAh · max 2 cái · chỉ xách tay", "deluxe": "≤20.000mAh · max 2 cái · chỉ xách tay", "skyboss": "≤20.000mAh · max 2 cái · chỉ xách tay", "important_notes": "Không được ký gửi, phải xách tay", "risk": 1, "short_answer": "\"Pin dự phòng ≤20.000mAh được mang xách tay, tối đa 2 cái, không ký gửi bạn nhé.\"", "escalate_when": "Pin >20.000mAh → không được mang"},
    {"category": "Hành lý", "situation": "Chất lỏng lên cabin", "promo_eco_basic": "≤100ml/chai · tổng ≤1L · túi zip trong suốt", "eco_standard": "≤100ml/chai · tổng ≤1L · túi zip trong suốt", "deluxe": "≤100ml/chai · tổng ≤1L · túi zip trong suốt", "skyboss": "≤100ml/chai · tổng ≤1L · túi zip trong suốt", "important_notes": "Quy định CAAV — áp dụng tất cả hạng vé", "risk": 1, "short_answer": "\"Chất lỏng ≤100ml/chai, tổng ≤1L, đựng túi zip trong suốt bạn nhé.\"", "escalate_when": "—"},
    {"category": "Hành lý", "situation": "Quá cân hành lý — phí", "promo_eco_basic": "Tính tại sân bay · tùy tuyến", "eco_standard": "Tính tại sân bay · tùy tuyến", "deluxe": "Tính tại sân bay · tùy tuyến", "skyboss": "Tính tại sân bay · tùy tuyến", "important_notes": "Giá tại sân bay cao hơn đặt trước", "risk": 2, "short_answer": "\"Phí quá cân tính tại sân bay và tùy tuyến, mình không có giá cụ thể lúc này bạn ơi.\"", "escalate_when": "Hỏi giá cụ thể → escalate hoặc link website VJ"},
    {"category": "Đổi vé", "situation": "Đổi ngày/giờ/hành trình", "promo_eco_basic": "Được · phí 378k nội địa 800k quốc tế/chặng/người", "eco_standard": "Được · phí 378k nội địa 800k quốc tế/chặng/người", "deluxe": "Được · phí 378k nội địa 800k quốc tế/chặng/người", "skyboss": "Miễn phí đổi nội địa & quốc tế", "important_notes": "Phải đổi trước 3 giờ khởi hành · Giá vé mới ≥ giá cũ", "risk": 2, "short_answer": "\"Được đổi ngày bạn nhé, phí 378k/người/chặng nội địa. Phải đổi trước giờ bay 3 tiếng.\"", "escalate_when": "User có booking → chuyển post-booking để thực hiện"},
    {"category": "Đổi vé", "situation": "Đổi tên hành khách", "promo_eco_basic": "Không được", "eco_standard": "Không được", "deluxe": "Không được", "skyboss": "Được · có phí (chỉ vé mua gốc SkyBoss)", "important_notes": "SkyBoss không đổi tên nếu vé nâng hạng hoặc thanh toán bằng bảo lưu", "risk": 2, "short_answer": "\"Eco/Promo/Deluxe không đổi tên được bạn nhé. SkyBoss mua gốc mới được đổi, có phí.\"", "escalate_when": "User muốn đổi tên thực tế → escalate"},
    {"category": "Đổi vé", "situation": "Thời hạn đổi", "promo_eco_basic": "Trước 3h khởi hành", "eco_standard": "Trước 3h khởi hành", "deluxe": "Trước 3h khởi hành", "skyboss": "Trước 3h khởi hành", "important_notes": "Áp dụng tất cả hạng vé", "risk": 1, "short_answer": "\"Đổi vé phải thực hiện trước giờ bay ít nhất 3 tiếng bạn nhé.\"", "escalate_when": "—"},
    {"category": "Đổi vé", "situation": "Giá vé mới khi đổi", "promo_eco_basic": "≥ giá vé ban đầu · chênh lệch thu ngay", "eco_standard": "≥ giá vé ban đầu · chênh lệch thu ngay", "deluxe": "≥ giá vé ban đầu · chênh lệch thu ngay", "skyboss": "≥ giá vé ban đầu · chênh lệch thu ngay", "important_notes": "Nếu vé mới rẻ hơn → không được hoàn phần chênh lệch", "risk": 2, "short_answer": "\"Vé mới phải cùng giá hoặc cao hơn bạn nhé, không đổi sang vé rẻ hơn được.\"", "escalate_when": "—"},
    {"category": "Hoàn vé", "situation": "Hoàn tự nguyện (không bay)", "promo_eco_basic": "Không hoàn Không bảo lưu", "eco_standard": "Không hoàn Không bảo lưu", "deluxe": "Bảo lưu định danh Phí 550k nội địa Bảo lưu 1 năm", "skyboss": "Bảo lưu định danh Phí 550k nội địa Bảo lưu 2 năm", "important_notes": "Yêu cầu hoàn trước 24h khởi hành · Promo = Eco không hoàn", "risk": 3, "short_answer": "\"Promo/Eco không hoàn tiền bạn nhé. Deluxe/SkyBoss được bảo lưu, phí 550k/người/chặng nội địa.\"", "escalate_when": "User có booking muốn hoàn → escalate ngay"},
    {"category": "Hoàn vé", "situation": "Phí hoàn — quốc tế", "promo_eco_basic": "—", "eco_standard": "—", "deluxe": "1.200.000đ/người/chặng (trừ chặng Úc)", "skyboss": "1.200.000đ/người/chặng (trừ chặng Úc)", "important_notes": "Chặng Úc: 2.400.000đ/người/chặng", "risk": 3, "short_answer": "\"Phí hoàn quốc tế 1,2 triệu/người/chặng bạn nhé (riêng chặng Úc 2,4 triệu).\"", "escalate_when": "User muốn hoàn thực tế → escalate"},
    {"category": "Hoàn vé", "situation": "Bảo lưu — thời hạn dùng", "promo_eco_basic": "—", "eco_standard": "—", "deluxe": "1 năm kể từ ngày khởi hành", "skyboss": "2 năm kể từ ngày khởi hành", "important_notes": "Tiền bảo lưu chỉ dùng cho người có tên trên vé gốc · Không hoàn tiền mặt", "risk": 2, "short_answer": "\"Tiền bảo lưu dùng được 1 năm (Deluxe) hoặc 2 năm (SkyBoss) và chỉ đặt cho đúng tên người bạn nhé.\"", "escalate_when": "—"},
    {"category": "Hoàn vé", "situation": "Hoàn khi hãng hủy chuyến", "promo_eco_basic": "Bảo lưu định danh 1 năm", "eco_standard": "Bảo lưu định danh 1 năm", "deluxe": "Bảo lưu định danh 1 năm", "skyboss": "Bảo lưu định danh 1 năm", "important_notes": "Hãng chậm/sớm >4h → bảo lưu · Chậm >5h → hoàn toàn bộ tiền vé", "risk": 3, "short_answer": "\"Nếu hãng hủy hoặc chậm hơn 4 tiếng, bạn được bảo lưu định danh 1 năm bạn nhé.\"", "escalate_when": "User đang trong tình huống này → escalate ngay · priority cao"},
    {"category": "Hoàn vé", "situation": "Lỡ chuyến (no-show)", "promo_eco_basic": "Không hoàn Mất vé", "eco_standard": "Không hoàn Mất vé", "deluxe": "Phí bỏ chỗ 250k nội địa 1 triệu quốc tế", "skyboss": "Phí bỏ chỗ 250k nội địa 1 triệu quốc tế", "important_notes": "Không đến làm thủ tục = mất vé với hạng Eco/Promo", "risk": 3, "short_answer": "\"Lỡ chuyến không check-in thì mất vé bạn ơi, Eco/Promo không hoàn được.\"", "escalate_when": "User vừa lỡ chuyến → escalate ngay · priority cao"},
    {"category": "Hoàn vé", "situation": "Hoàn bất khả kháng (ốm, tai nạn)", "promo_eco_basic": "Bảo lưu định danh miễn phí (cần giấy tờ chứng minh)", "eco_standard": "Bảo lưu định danh miễn phí (cần giấy tờ chứng minh)", "deluxe": "Bảo lưu định danh miễn phí (cần giấy tờ chứng minh)", "skyboss": "Bảo lưu định danh miễn phí (cần giấy tờ chứng minh)", "important_notes": "Cần giấy bệnh viện / tai nạn hợp lệ · Liên hệ VJ trực tiếp", "risk": 3, "short_answer": "\"Trường hợp bất khả kháng được bảo lưu miễn phí, cần cung cấp giấy tờ chứng minh bạn nhé.\"", "escalate_when": "Escalate ngay — cần xét duyệt riêng từng case"},
    {"category": "Hành khách đặc biệt", "situation": "Trẻ em dưới 2 tuổi (Infant)", "promo_eco_basic": "Cần mua vé · ngồi lòng người lớn · không có ghế riêng", "eco_standard": "Cần mua vé · ngồi lòng người lớn · không có ghế riêng", "deluxe": "Cần mua vé · ngồi lòng người lớn · không có ghế riêng", "skyboss": "Cần mua vé · ngồi lòng người lớn · không có ghế riêng", "important_notes": "Giá vé Infant theo quy định VJ · cần khai báo khi đặt", "risk": 1, "short_answer": "\"Bé dưới 2 tuổi cần mua vé riêng nhưng ngồi lòng người lớn, không có ghế riêng bạn nhé.\"", "escalate_when": "—"},
    {"category": "Hành khách đặc biệt", "situation": "Trẻ em 2–12 tuổi (Child)", "promo_eco_basic": "Mua vé như người lớn · cần giấy khai sinh hoặc hộ chiếu", "eco_standard": "Mua vé như người lớn · cần giấy khai sinh hoặc hộ chiếu", "deluxe": "Mua vé như người lớn · cần giấy khai sinh hoặc hộ chiếu", "skyboss": "Mua vé như người lớn · cần giấy khai sinh hoặc hộ chiếu", "important_notes": "Trẻ dưới 12 tuổi không được đi một mình", "risk": 1, "short_answer": "\"Trẻ 2–12 tuổi mua vé bình thường, cần mang giấy khai sinh hoặc hộ chiếu bạn nhé.\"", "escalate_when": "Trẻ đi một mình → escalate xác nhận riêng"},
    {"category": "Hành khách đặc biệt", "situation": "Phụ nữ mang thai", "promo_eco_basic": "≤32 tuần: được bay có giấy bác sĩ >32 tuần: không bay", "eco_standard": "≤32 tuần: được bay có giấy bác sĩ >32 tuần: không bay", "deluxe": "≤32 tuần: được bay có giấy bác sĩ >32 tuần: không bay", "skyboss": "≤32 tuần: được bay có giấy bác sĩ >32 tuần: không bay", "important_notes": "Đa thai: giới hạn thấp hơn · Cần xác nhận trực tiếp với VJ", "risk": 2, "short_answer": "\"Thai trên 32 tuần thường không được bay bạn nhé. Bạn đang ở tuần thai bao nhiêu?\"", "escalate_when": "Thai gần hạn / đa thai → escalate để xác nhận với VJ"},
    {"category": "Hành khách đặc biệt", "situation": "Giấy tờ bay nội địa", "promo_eco_basic": "CMND / CCCD / Hộ chiếu còn hạn", "eco_standard": "CMND / CCCD / Hộ chiếu còn hạn", "deluxe": "CMND / CCCD / Hộ chiếu còn hạn", "skyboss": "CMND / CCCD / Hộ chiếu còn hạn", "important_notes": "Áp dụng cho người Việt Nam · Người nước ngoài cần hộ chiếu", "risk": 1, "short_answer": "\"Bay nội địa cần CMND, CCCD hoặc hộ chiếu còn hạn là đủ bạn nhé.\"", "escalate_when": "—"},
    {"category": "Hành khách đặc biệt", "situation": "Hộ chiếu bay quốc tế", "promo_eco_basic": "Thường cần còn ≥6 tháng · tùy điểm đến", "eco_standard": "Thường cần còn ≥6 tháng · tùy điểm đến", "deluxe": "Thường cần còn ≥6 tháng · tùy điểm đến", "skyboss": "Thường cần còn ≥6 tháng · tùy điểm đến", "important_notes": "Tùy điểm đến — phải check từng quốc gia", "risk": 2, "short_answer": "\"Thường cần hộ chiếu còn ít nhất 6 tháng bạn ơi. Bạn đi đâu để mình kiểm tra chính xác hơn?\"", "escalate_when": "Hỏi cụ thể từng quốc gia → link iatatravelcentre.com"},
    {"category": "Hành khách đặc biệt", "situation": "Visa quốc tế", "promo_eco_basic": "Tùy quốc tịch · tùy điểm đến", "eco_standard": "Tùy quốc tịch · tùy điểm đến", "deluxe": "Tùy quốc tịch · tùy điểm đến", "skyboss": "Tùy quốc tịch · tùy điểm đến", "important_notes": "VN thường miễn visa Thái/Sing ≤30 ngày · cần xác nhận lại", "risk": 2, "short_answer": "\"Người Việt thường miễn visa Thái/Sing ≤30 ngày, nhưng nên kiểm tra lại vì hay thay đổi bạn nhé.\"", "escalate_when": "Quốc tịch khác / transit phức tạp → link IATA Travel Centre"},
    {"category": "Thanh toán & giá vé", "situation": "Phương thức thanh toán trên MoMo", "promo_eco_basic": "Ví MoMo · thẻ nội địa · thẻ quốc tế · tài khoản liên kết", "eco_standard": "Ví MoMo · thẻ nội địa · thẻ quốc tế · tài khoản liên kết", "deluxe": "Ví MoMo · thẻ nội địa · thẻ quốc tế · tài khoản liên kết", "skyboss": "Ví MoMo · thẻ nội địa · thẻ quốc tế · tài khoản liên kết", "important_notes": "← CS Manager xác nhận danh sách đầy đủ với MoMo team", "risk": 1, "short_answer": "\"Trên MoMo bạn thanh toán được bằng ví MoMo, thẻ nội/ngoại địa hoặc tài khoản ngân hàng liên kết.\"", "escalate_when": "—"},
    {"category": "Thanh toán & giá vé", "situation": "Đã trừ tiền chưa có vé", "promo_eco_basic": "Lỗi giao dịch · cần xác minh ngay", "eco_standard": "Lỗi giao dịch · cần xác minh ngay", "deluxe": "Lỗi giao dịch · cần xác minh ngay", "skyboss": "Lỗi giao dịch · cần xác minh ngay", "important_notes": "Priority cao — không để user chờ", "risk": 3, "short_answer": "\"Mình hiểu đây rất bất tiện. Bạn cho mình mã giao dịch để xử lý ngay nhé.\"", "escalate_when": "Escalate NGAY · priority cao · thu mã giao dịch + kênh thanh toán"},
    {"category": "Thanh toán & giá vé", "situation": "Mua vé sớm có rẻ hơn?", "promo_eco_basic": "Thường có · không đảm bảo", "eco_standard": "Thường có · không đảm bảo", "deluxe": "Thường có · không đảm bảo", "skyboss": "Thường có · không đảm bảo", "important_notes": "VJ hay có sale bất ngờ · không có quy tắc cố định", "risk": 1, "short_answer": "\"Thường mua sớm rẻ hơn, nhưng VJ cũng hay có sale bất ngờ bạn nhé, theo dõi thêm.\"", "escalate_when": "—"},
    {"category": "Thanh toán & giá vé", "situation": "Khứ hồi rẻ hơn một chiều?", "promo_eco_basic": "Không nhất thiết · tùy tuyến & thời điểm", "eco_standard": "Không nhất thiết · tùy tuyến & thời điểm", "deluxe": "Không nhất thiết · tùy tuyến & thời điểm", "skyboss": "Không nhất thiết · tùy tuyến & thời điểm", "important_notes": "Có thể mua 2 chiều riêng rẻ hơn", "risk": 1, "short_answer": "\"Không hẳn bạn ơi, tùy tuyến và thời điểm, đôi khi mua 2 chiều riêng lại rẻ hơn.\"", "escalate_when": "—"},
    {"category": "Thanh toán & giá vé", "situation": "Mua vé cho người khác", "promo_eco_basic": "Được · điền đúng tên người đi", "eco_standard": "Được · điền đúng tên người đi", "deluxe": "Được · điền đúng tên người đi", "skyboss": "Được · điền đúng tên người đi", "important_notes": "Tên phải khớp chính xác với giấy tờ tùy thân", "risk": 1, "short_answer": "\"Được bạn nhé, cần điền đúng tên và ngày sinh của người đi theo giấy tờ tùy thân.\"", "escalate_when": "—"},
]

