version: '3.8'
services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: rag_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: